### ISSUE TITLE
Ensure that NPM points here

### ISSUE THREAD

**Issue by robertleeplummerjr** [zemlyansky/gpt-tfjs#1]
It would be very useful for [your package](https://www.npmjs.com/package/gpt-tfjs) on npmjs.com to point back here for people to be able to collaborate and to understand better.

Great job overall.

**Comment by robertleeplummerjr** [comment]
It cannot be overstated the importance of being able to train these models in javascript, which I've never seen another project do.  They generally only show how to run models.  That is about 1/4-ish what the model does.  Training it is a much better end to end demonstration of capabilities, even if it isn't practical in javascript.

**Comment by zemlyansky** [comment]
Thanks for the suggestion and kind words @robertleeplummerjr! I've just published [v0.0.5](https://github.com/zemlyansky/gpt-tfjs/releases/tag/v0.0.5) to npm and added a link to the repo: https://www.npmjs.com/package/gpt-tfjs/v/0.0.5

> It cannot be overstated the importance of being able to train these models in javascript...

Agree 100%! More people could play with them and understand how the models work. Or even fine-tune something not too big

**Comment by robertleeplummerjr** [comment]
You rock.
